apiVersion: v1
kind: Service
metadata:
  name: catsdogs-api-service
  labels:
    app: catsdogs-api
spec:
  type: LoadBalancer
  selector:
    app: catsdogs-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: catsdogs-api-nodeport
  labels:
    app: catsdogs-api
spec:
  type: NodePort
  selector:
    app: catsdogs-api
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
